export const CATEGORIES = [
  { id:'all',  label:'All Projects', count: 48 },
  { id:'ml',   label:'Machine Learning', count: 14 },
  { id:'dl',   label:'Deep Learning', count: 11 },
  { id:'cv',   label:'Computer Vision', count: 8 },
  { id:'web',  label:'Web Applications', count: 9 },
  { id:'mob',  label:'Mobile Applications', count: 6 },
];

export const PROJECTS = [
  { id:'p01', cat:'ml', title:'Credit Risk Scoring Engine', tag:'Classification', price:1499, level:'Intermediate', stack:['Python','scikit-learn','XGBoost','Streamlit'], rating:4.9, downloads:1284, color:'#2A2FB8', desc:'End-to-end pipeline that ingests LendingClub-style data, engineers 42 features, and scores default probability with an XGBoost ensemble. Ships with a Streamlit dashboard for loan officers.', files:38, pages:62, includes:['Full source code','Cleaned dataset (270MB)','Jupyter notebooks','Final year report (PDF, 62pp)','Deployment on Render','IEEE paper references'], youtubeLink: 'https://youtu.be/o839d-6Xf3I' },
  { id:'p02', cat:'dl', title:'Real-time Sign Language Translator', tag:'LSTM + MediaPipe', price:1999, level:'Advanced', stack:['PyTorch','MediaPipe','OpenCV','Flask'], rating:4.9, downloads:2103, color:'#0A0F2C', desc:'Translates 100 ASL gestures to text at 28 FPS using a 3-stream LSTM over MediaPipe landmarks. Webcam demo included.', files:54, pages:78, includes:['Trained weights','Gesture dataset','Live webcam demo','Report + slides','Setup guide','1 month Q&A support'], youtubeLink: 'https://youtu.be/o839d-6Xf3I' },
  { id:'p03', cat:'cv', title:'Retinal Disease Detection', tag:'CNN, Grad-CAM', price:2299, level:'Advanced', stack:['TensorFlow','EfficientNet','Grad-CAM'], rating:5.0, downloads:892, color:'#1A1F7A', desc:'Fine-tuned EfficientNet-B3 detects 5 retinal conditions from fundus images with 94.2% test accuracy. Grad-CAM visualises attention.', files:41, pages:70, includes:['Pre-trained model','APTOS dataset','Grad-CAM notebook','Thesis-ready report','Reference papers'], youtubeLink: 'https://youtu.be/o839d-6Xf3I' },
  { id:'p04', cat:'web', title:'Smart Resume Analyzer', tag:'NLP + MERN', price:1199, level:'Beginner', stack:['React','Node','MongoDB','spaCy'], rating:4.7, downloads:3421, color:'#FF8A5C', desc:'Upload a résumé, get a skill-gap report scored against any JD. Full MERN app with JWT auth and PDF parsing.', files:62, pages:54, includes:['Frontend + backend source','MongoDB schema','Dockerfile','Report + architecture','Live demo on Vercel'], youtubeLink: 'https://youtu.be/o839d-6Xf3I' },
  { id:'p05', cat:'mob', title:'Crop Disease Scanner', tag:'Flutter + TFLite', price:1799, level:'Intermediate', stack:['Flutter','TFLite','Firebase'], rating:4.8, downloads:1507, color:'#2A2FB8', desc:'On-device classifier identifies 38 crop diseases from a phone camera. Works offline. Firebase sync for farmer history.', files:47, pages:58, includes:['Flutter source','TFLite model','PlantVillage dataset','APK build','Setup walkthrough video'], youtubeLink: 'https://youtu.be/o839d-6Xf3I' },
  { id:'p06', cat:'ml', title:'Customer Churn Predictor', tag:'Random Forest', price:899, level:'Beginner', stack:['Python','pandas','Flask'], rating:4.6, downloads:2298, color:'#1A1F7A', desc:'Predicts telecom churn with 89% F1. Flask API + bootstrap dashboard for account managers.', files:28, pages:48, includes:['Source code','Telco dataset','Feature importance notebook','Report','Deployment guide'], youtubeLink: 'https://youtu.be/o839d-6Xf3I' },
  { id:'p07', cat:'dl', title:'Fake News BERT Classifier', tag:'Transformers', price:1699, level:'Intermediate', stack:['HuggingFace','PyTorch','FastAPI'], rating:4.8, downloads:1876, color:'#0A0F2C', desc:'Fine-tuned DistilBERT flags misinformation in English news with 96% accuracy. FastAPI + simple React frontend.', files:36, pages:66, includes:['Model checkpoint','LIAR + custom dataset','Training notebooks','Report','API docs'], youtubeLink: 'https://youtu.be/o839d-6Xf3I' },
  { id:'p08', cat:'cv', title:'Traffic Sign Recognition', tag:'YOLOv8', price:1499, level:'Intermediate', stack:['YOLOv8','OpenCV','PyQt'], rating:4.7, downloads:1203, color:'#2A2FB8', desc:'Detects 43 GTSRB traffic signs in real time with a PyQt desktop viewer. Webcam or video file input.', files:33, pages:55, includes:['Trained YOLO weights','GTSRB dataset','Desktop app','Report','Reference papers'], youtubeLink: 'https://youtu.be/o839d-6Xf3I' },
  { id:'p09', cat:'web', title:'AI Interview Coach', tag:'LLM + WebRTC', price:2699, level:'Advanced', stack:['Next.js','OpenAI','WebRTC','Prisma'], rating:4.9, downloads:714, color:'#FF8A5C', desc:'Conducts mock interviews with voice, scores answers on STAR rubric, and emits a rubric-based report.', files:71, pages:82, includes:['Next.js source','Prompt templates','Prisma schema','Deployment guide','30-day support'], youtubeLink: 'https://youtu.be/o839d-6Xf3I' },
  { id:'p10', cat:'ml', title:'Movie Recommender (Hybrid)', tag:'Collab + Content', price:1099, level:'Beginner', stack:['Python','Surprise','Streamlit'], rating:4.6, downloads:2541, color:'#1A1F7A', desc:'Hybrid recommender combining matrix factorization with TF-IDF content similarity on MovieLens-25M.', files:24, pages:46, includes:['Source code','MovieLens subset','Streamlit demo','Report','Evaluation notebook'], youtubeLink: 'https://youtu.be/o839d-6Xf3I' },
  { id:'p11', cat:'mob', title:'Personal Finance Tracker', tag:'React Native', price:1399, level:'Intermediate', stack:['React Native','Expo','Supabase'], rating:4.8, downloads:1129, color:'#2A2FB8', desc:'Cross-platform expense tracker with OCR receipts, budget rules, and Supabase sync. Ships iOS + Android.', files:52, pages:50, includes:['Expo source','Supabase schema','Tesseract OCR module','Setup guide','Report'], youtubeLink: 'https://youtu.be/o839d-6Xf3I' },
  { id:'p12', cat:'dl', title:'Music Genre Classifier', tag:'CNN Spectrograms', price:1299, level:'Intermediate', stack:['Librosa','Keras','Gradio'], rating:4.7, downloads:1682, color:'#0A0F2C', desc:'Classifies 10 genres from 30s clips using mel-spectrograms and a compact CNN. Gradio demo included.', files:29, pages:52, includes:['Model + weights','GTZAN dataset','Gradio app','Report','Notebook walkthrough'], youtubeLink: 'https://youtu.be/o839d-6Xf3I' },
];

export const STACKS: Record<string, any> = {
  p01: { kind:'ml', algorithm:'XGBoost Classifier (n=400)', dataset:'LendingClub · 890k rows', accuracy:'AUC 0.891 · F1 0.78', training:'Stratified k-fold, focal loss', frontend:['Streamlit dashboard'], backend:['Python 3.11','FastAPI','SHAP'], db:['PostgreSQL','Redis cache'], deploy:['Render','Docker'] },
  p02: { kind:'dl', algorithm:'3-stream LSTM (hand/body/face)', dataset:'Custom ASL · 20k clips, 100 classes', accuracy:'92.6% top-1 · 28 FPS', training:'Adam, focal loss, 80 epochs', frontend:['Flask web demo','WebRTC camera'], backend:['PyTorch','MediaPipe','OpenCV'], db:['SQLite (session logs)'], deploy:['Docker','NVIDIA T4'] },
  p03: { kind:'dl', algorithm:'EfficientNet-B3 (fine-tuned)', dataset:'APTOS 2019 + Messidor-2 · 21k', accuracy:'94.2% · κ 0.89', training:'Transfer learning, focal loss', frontend:['Streamlit app','Grad-CAM overlay'], backend:['TensorFlow 2.15','Keras'], db:['PostgreSQL','DICOM store'], deploy:['Docker','GCP Vertex AI'] },
  p04: { kind:'web', frontend:['React 18','Tailwind CSS','Vite'], backend:['Node.js','Express','spaCy','pdfplumber'], db:['MongoDB Atlas','Redis'], auth:['JWT','bcrypt'], deploy:['Vercel (FE)','Render (BE)','S3 uploads'] },
  p05: { kind:'mob', frontend:['Flutter 3.22','Dart'], backend:['TFLite runtime','On-device inference'], db:['Firebase Firestore','SQLite (offline)'], model:'MobileNetV3-small · INT8 · 4.1 MB', accuracy:'95.1% · 180 ms/infer', deploy:['Play Store','Firebase App Distribution'] },
  p06: { kind:'ml', algorithm:'Random Forest (n=300)', dataset:'IBM Telco Churn · 7,043 rows', accuracy:'F1 0.89 · ROC-AUC 0.87', training:'Class-weighted, RFE', frontend:['Bootstrap 5 dashboard'], backend:['Python','Flask','scikit-learn'], db:['SQLite','CSV export'], deploy:['Heroku','Docker'] },
  p07: { kind:'dl', algorithm:'DistilBERT (fine-tuned)', dataset:'LIAR + Kaggle Fake News · 38k', accuracy:'96.1% · F1 macro 0.95', training:'HuggingFace Trainer, 4 epochs', frontend:['React 18','highlight.js'], backend:['FastAPI','HuggingFace Transformers'], db:['PostgreSQL','pgvector'], deploy:['Fly.io','NVIDIA T4'] },
  p08: { kind:'dl', algorithm:'YOLOv8-small + Kalman tracker', dataset:'GTSRB + Custom IN · 57k images', accuracy:'mAP@0.5 · 0.971', training:'Ultralytics, 100 epochs', frontend:['PyQt6 desktop app'], backend:['YOLOv8','OpenCV','NumPy'], db:['CSV logs','SQLite'], deploy:['PyInstaller bundle'] },
  p09: { kind:'web', frontend:['Next.js 14','React','Tailwind','WebRTC'], backend:['Node.js','OpenAI GPT-4o','Whisper-v3'], db:['PostgreSQL','Prisma ORM'], auth:['NextAuth','OAuth Google'], deploy:['Vercel','Railway'] },
  p10: { kind:'ml', algorithm:'SVD++ + TF-IDF hybrid', dataset:'MovieLens-25M', accuracy:'RMSE 0.79 · 11% cold-start lift', training:'Surprise library, grid search', frontend:['Streamlit demo'], backend:['Python','Surprise','scikit-learn'], db:['Parquet + DuckDB'], deploy:['Streamlit Cloud'] },
  p11: { kind:'mob', frontend:['React Native','Expo SDK 52'], backend:['Tesseract.js','Node services'], db:['Supabase PostgreSQL','Row-level security'], auth:['Supabase Auth','Biometrics'], deploy:['EAS Build','Play Store','App Store'] },
  p12: { kind:'dl', algorithm:'5-layer CNN on mel-spectrograms', dataset:'GTZAN · 1,000 × 30s clips', accuracy:'89.7% · <80 ms infer', training:'Adam + mixup, 60 epochs', frontend:['Gradio web UI'], backend:['Keras','Librosa','NumPy'], db:['HDF5 feature cache'], deploy:['HuggingFace Spaces'] },
};

export const ABSTRACTS: Record<string, any> = {
  p01: { objective:'Build a production-ready credit-risk scoring engine that approves or declines loan applications with calibrated default probabilities and human-readable reasons.', methodology:'Ingested 890k LendingClub-style records; engineered 42 features including debt-to-income, credit-line utilisation, and employment tenure. Trained an XGBoost ensemble (n=400) with stratified k-fold validation. SHAP values expose feature contributions per applicant.', results:'ROC-AUC of 0.891 on the held-out set, F1 of 0.78 on the minority class. Decision thresholds are tunable from a Streamlit dashboard. Outperforms a logistic-regression baseline by 12.4 AUC points.', keywords:'credit scoring, XGBoost, SHAP, risk analytics, fintech' },
  p02: { objective:'Translate American Sign Language in real time from a standard webcam so deaf students can participate in hybrid classrooms without a human interpreter.', methodology:'Extract 21 hand + 33 body + 468 face landmarks with MediaPipe Holistic. Feed three parallel LSTM streams (hand, body, face) into a fused dense head trained with focal loss on a 100-class, 20k-clip dataset.', results:'28 FPS end-to-end on a 2020 laptop CPU with 92.6% top-1 accuracy across 100 gestures. Flask demo streams webcam to predictions in under 120 ms.', keywords:'sign language, LSTM, MediaPipe, accessibility, gesture recognition' },
  p03: { objective:'Screen five retinal conditions (DR, glaucoma, AMD, cataract, hypertensive retinopathy) from single fundus photographs to assist ophthalmologists in under-served clinics.', methodology:'Fine-tuned EfficientNet-B3 pretrained on ImageNet using the APTOS 2019 + Messidor-2 combined dataset (21k images). Class imbalance mitigated with focal loss and online augmentation. Grad-CAM overlays visualise attention.', results:'94.2% test accuracy, quadratic-weighted kappa of 0.89. Grad-CAM heatmaps correctly localise pathology in 87% of positive cases, validated by two retinal specialists.', keywords:'medical imaging, EfficientNet, Grad-CAM, retinal disease, transfer learning' },
  p04: { objective:'Give candidates a structured skill-gap report between any resume and any job description, reducing blind applications for first-time job seekers.', methodology:'PDF parsing with pdfplumber; spaCy NER + rule-based matchers extract skills, education, and experience. Cosine similarity scores resume against a JD-derived skill vector. MERN stack with JWT auth, uploads on S3, server-side PDF render for the report.', results:'Analyses a 2-page resume in 3.4 s on average. Extraction F1 of 0.82 on the Rezi benchmark. Live deployment on Vercel + Render scales to 500 concurrent users.', keywords:'NLP, resume parsing, skill matching, MERN, spaCy' },
  p05: { objective:'Put a crop-disease diagnostician in every farmer pocket, working fully offline in low-connectivity villages.', methodology:'MobileNetV3-small trained on the PlantVillage dataset (54k images, 38 classes) in TensorFlow; quantised to INT8 and converted to TFLite (4.1 MB). Flutter UI captures the leaf, runs inference on-device, and caches history to Firebase when a network returns.', results:'95.1% top-1 accuracy on-device, median inference 180 ms on an 8,000-rupee Android phone. Pilot with 40 farmers in Maharashtra cut misdiagnosis by 61% vs. WhatsApp-group consultation.', keywords:'agriculture, TFLite, on-device ML, Flutter, PlantVillage' },
  p06: { objective:'Predict which telecom customers will cancel in the next 30 days so retention teams can target interventions before notice is given.', methodology:'Analysed the IBM Telco Churn dataset (7,043 customers, 21 features). Engineered tenure buckets and service-bundle counts; trained a Random Forest (n=300) with class-weight balancing and recursive feature elimination.', results:'F1 of 0.89 on the churn class; top three drivers were contract type, tenure, and monthly charges. A Flask API with a Bootstrap dashboard surfaces a ranked at-risk list to account managers.', keywords:'churn prediction, Random Forest, telecom, feature engineering, Flask' },
  p07: { objective:'Flag English-language news articles as likely misinformation with a transparent confidence score and evidence highlights.', methodology:'Fine-tuned DistilBERT on a combined LIAR + Kaggle Fake News corpus (38k articles). Applied label smoothing and gradient accumulation. FastAPI wraps the inference pipeline; a React frontend highlights the spans that swayed the verdict.', results:'96.1% test accuracy, 0.95 F1 macro. Average inference 45 ms per article on a single T4 GPU.', keywords:'misinformation, DistilBERT, transformers, fact-checking, FastAPI' },
  p08: { objective:'Recognise Indian + German traffic signs in real time to form the perception layer of a driver-assistance prototype.', methodology:'Trained YOLOv8-small on GTSRB (43 classes, 51k images) augmented with a custom 6k-image Indian subset. Post-processing with non-max suppression and a Kalman-filter tracker stabilises detections across frames.', results:'mAP@0.5 of 0.971, 58 FPS on a GTX 1660. A PyQt desktop viewer accepts webcam or video-file input and logs detections to CSV.', keywords:'YOLOv8, object detection, ADAS, traffic signs, computer vision' },
  p09: { objective:'Simulate a behavioural-round interview with voice, grade answers on the STAR rubric, and return a personalised improvement plan.', methodology:'Next.js + WebRTC capture candidate audio; Whisper-v3 transcribes; GPT-4o scores each answer across Situation/Task/Action/Result using few-shot prompts with JSON mode. Prisma persists sessions for coaching longitudinally.', results:'Inter-rater agreement with 3 human coaches: Cohen kappa = 0.71. Mean STAR score improved by 28% across a 20-user pilot over three sessions.', keywords:'LLM, interview coaching, WebRTC, STAR rubric, Next.js' },
  p10: { objective:'Recommend movies to new and active users with a single model that degrades gracefully on cold starts.', methodology:'Hybrid recommender: Surprise SVD++ for collaborative filtering on MovieLens-25M; TF-IDF over tags + genres for content similarity. Scores blended with a learned alpha per user based on rating history depth.', results:'RMSE of 0.79 on the standard split, 11% better than a pure-CF baseline on cold-start users (< 5 ratings). Streamlit demo serves sub-200 ms responses.', keywords:'recommender systems, SVD, TF-IDF, MovieLens, hybrid model' },
  p11: { objective:'Replace shoebox receipts and spreadsheets with a cross-platform expense tracker that auto-categorises spending.', methodology:'React Native + Expo UI; Tesseract.js in a native module OCRs receipt images; heuristic + keyword rules assign a category from 28 presets. Supabase stores transactions, budgets, and user preferences with row-level security.', results:'OCR field accuracy (vendor, total, date) of 91% on a 500-receipt benchmark. Ships iOS + Android from a single codebase; cold-start to home screen in 1.6 s.', keywords:'personal finance, OCR, React Native, Supabase, budget tracking' },
  p12: { objective:'Classify music clips into 10 genres to power a listen-alike recommendation widget for an indie streaming site.', methodology:'Convert 30-second GTZAN clips to 128-bin mel-spectrograms with Librosa; train a 5-layer CNN (approx 230k parameters) with mixup augmentation. Gradio demo accepts file uploads or live mic input.', results:'Test accuracy of 89.7% across 10 genres; confusion concentrated in rock/metal and disco/pop, consistent with human labellers. Inference under 80 ms on CPU.', keywords:'audio classification, CNN, mel-spectrogram, GTZAN, Gradio' },
};

export const BUNDLES = [
  { id:'portfolio', name:'Portfolio Pack', price:3999, tagline:'For a graduating class', features:['Any 3 projects, any category','Full source + datasets','Reports + slide decks','Deployment walkthrough','30-day live support','Private mentor review call'], cta:'Get portfolio pack' },
  { id:'solo', name:'Solo Project', price:1499, featured:true, tagline:'For a single capstone', features:['Pick any 1 project','Full source + dataset','Report + slides','Setup guide','7-day Q&A support'], cta:'Buy single project' },
  { id:'studio', name:'Department Licence', price:14999, tagline:'For a cohort or institution', features:['All 48 projects, all updates','Classroom licence (up to 40 students)','Private help channel','Instructor deck + rubric','90-day priority support','Quarterly new-project drop'], cta:'Talk to us' },
];

export const TWEAK_DEFAULTS = {
  "accent": "#FF8A5C"
};

export const ADD_ONS = [
  { id: 'src',     label: 'Source Code',          desc: 'Complete, runnable codebase',         price: 599,  icon: '💻', required: true  },
  { id: 'report',  label: 'Project Report',       desc: 'Thesis-ready PDF (50–80 pages)',       price: 299,  icon: '📄', required: false },
  { id: 'slides',  label: 'Presentation Slides',  desc: 'PPT/PPTX viva deck (20–30 slides)',   price: 149,  icon: '🖼️', required: false },
  { id: 'data',    label: 'Dataset',              desc: 'Cleaned, labelled, ready to train',   price: 199,  icon: '🗄️', required: false },
  { id: 'nb',      label: 'Notebooks',            desc: 'Step-by-step Jupyter walkthroughs',   price: 149,  icon: '📓', required: false },
  { id: 'deploy',  label: 'Deployment Guide',     desc: 'Docker / Vercel / Render setup',      price: 99,   icon: '🚀', required: false },
  { id: 'papers',  label: 'Reference Papers',     desc: 'Curated IEEE/ACM PDFs with notes',    price: 99,   icon: '📚', required: false },
  { id: 'viva',    label: 'Viva Q&A Guide',       desc: 'Project-specific panel questions',    price: 149,  icon: '🎓', required: false },
  { id: 'support', label: '1-Month Support',      desc: 'WhatsApp Q&A with the author',        price: 299,  icon: '💬', required: false },
];

export const ADD_ONS_INIT: Record<string, boolean> = ADD_ONS.reduce(
  (a, i) => ({ ...a, [i.id]: i.required }),
  {}
);

export const ADD_ONS_FULL = ADD_ONS.reduce((s, i) => s + i.price, 0);

export const VIVA_TABS = [
  { id: 'ml',  label: 'Machine Learning', icon: '🤖' },
  { id: 'dl',  label: 'Deep Learning',    icon: '🧠' },
  { id: 'cv',  label: 'Computer Vision',  icon: '👁️' },
  { id: 'web', label: 'Web Applications', icon: '🌐' },
  { id: 'mob', label: 'Mobile Apps',      icon: '📱' },
];
